namespace GdaxPrototyping.Common.Core.Diagnostics
{
   [System.Runtime.Serialization.DataContractAttribute()]
   [System.Security.SuppressUnmanagedCodeSecurityAttribute()]
   public sealed class TLoggingHelpersConfiguration
   {
      #region Data.

      [System.Runtime.Serialization.IgnoreDataMemberAttribute()]
      public string BaseDirectoryPathName { get; private set; }

      /// <summary>
      /// todo.1 Is this comment relevant?
      /// Comment201710027 applies.
      /// </summary>
      [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
      public string MainLogFilePathName;

      #endregion

      #region {public} Instance default constructor.

      // Could be autogenerated.

      #endregion

      #region {public Prepare}.

      public void Prepare
         ( string baseDirectoryPathName1
         )
      {
         BaseDirectoryPathName = baseDirectoryPathName1;
      }

      #endregion
   }
}
